# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'weather-app'
target 'weather-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather-app
  pod 'SwiftSoup'
  pod 'NVActivityIndicatorView'
 
  target 'weather-appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weather-appUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
