project 'tinder-style-app.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tinder-style-app' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Parse'
  
  # Pods for tinder-style-app

end
